### PR TITLE
Some changes in website presentation.

### PR DESCRIPTION
**Pull request by faustinoaq**
This PR does:

- Add video animation by @elorest.
- Update documentation link to https://docs.ambercr.io

amberio

The video was taken from https://twitter.com/elorest/status/905699362193342464

### CODE REVIEW

**Comment by elorest** [comment]
We should probably put that in the readme as well. Seems like projects that
start off with something like that always get starred higher.

Isaac Sloan - isaacsloan.com
Artisan Rails Architect
1391 S Slate Canyon Dr.
Provo, Ut 84606
Cell: (435)-669-5005

**Comment by faustinoaq** [comment]
@elorest I agree, Maybe we can put the video in the docs page because README doesn't allow video and a gif is too heavy.

**Comment by elorest** [comment]
There are a large amount of Readme's that have gifs in them. This one has
multiple gifs. https://github.com/rhysd/vim-crystal

Isaac Sloan - isaacsloan.com
Artisan Rails Architect
1391 S Slate Canyon Dr.
Provo, Ut 84606
Cell: (435)-669-5005

**Comment by faustinoaq** [comment]
Oh, I see, I will publish another PR to add some gifs to the README :+1: 

Is this PR ready to be merged?

**Comment by elorest** [comment]
Yeah I believe so.


Isaac Sloan - isaacsloan.com
Artisan Rails Architect
1391 S Slate Canyon Dr.
Provo, Ut 84606
Cell: (435)-669-5005

**Pull request merged**
